#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu /var/www/html
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx start
